# Site settings
title:
email: juanekipes@gmail.com
author:
description:
url:

environment: development
show_drafts: true

# Social icons
show_social_icons: true
github_username: juanek
pinterest_username: jkipes

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: full

# plugins
plugins: [jekyll-paginate]
paginate: 3
