# Site settings
title:
email: juanekipes@gmail.com
author:
description:
url:

environment: production
show_drafts: false

# Social icons
show_social_icons: true
github_username: juanek
#pinterest_username: jkipes
#twitter_username: juanek

disqus:
    shortname: juanekipes
google_analytics: UA-126646878-1


# Build settings
permalink: :title/
sass:
  sass_dir: css

# plugins
plugins: [jekyll-paginate]
paginate: 3
