# Site settings
title: Juan E. Kipes Blog
email: juanekipes@gmail.com
author: Juan E. Kipes
description: Un blog dedicado al desarrollo de software, lenguaje Java , administración linux y herramientas para aplicaciones web en general.
url: https://juanekipes.tk
lang: es_AR

environment: production
show_drafts: false

# Social icons
show_social_icons: true
github_username: juanek
#pinterest_username: jkipes
#twitter_username: juanek

disqus:
    shortname: juanekipes
google_analytics: UA-126646878-1


# Build settings
permalink: :title/
sass:
  sass_dir: css

# plugins
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate: 3
