# Site settings
title: Juan E. Kipes Blog
email: juanekipes@gmail.com
author: Juan E. Kipes
description: Un blog dedicado al desarrollo de software, lenguaje Java , administración linux y herramientas para aplicaciones web en general.
url: https://juanek.github.io/jekyll-blog
lang: es_AR

environment: development
show_drafts: true

# Social icons
show_social_icons: true
github_username: juanek
#pinterest_username: jkipes

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: full

# plugins
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate: 3
